// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMp6W73dinTqCJNEW0jhIVzU-NYyVTvnI',
    appId: '1:681173366559:web:844212427271ba64d7e22a',
    messagingSenderId: '681173366559',
    projectId: 'dry-needling-48b83',
    authDomain: 'dry-needling-48b83.firebaseapp.com',
    storageBucket: 'dry-needling-48b83.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-rt2Wz9OIwhJhHQd9U2JBvH9vFof2Q7U',
    appId: '1:681173366559:android:9ecffa42eb564e2ad7e22a',
    messagingSenderId: '681173366559',
    projectId: 'dry-needling-48b83',
    storageBucket: 'dry-needling-48b83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhWA_zqyLbklJe5SC9Z4-0iLDSRO00FyA',
    appId: '1:681173366559:ios:b55a73c388ce68b2d7e22a',
    messagingSenderId: '681173366559',
    projectId: 'dry-needling-48b83',
    storageBucket: 'dry-needling-48b83.firebasestorage.app',
    iosBundleId: 'com.example.dryNeedling',
  );
}
